apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: finalhello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: finalhello
    spec:
      containers:
      - name: finalhello
        image: anushka297/get-started:sayhey
        ports:
        - containerPort: 80

